### ISSUE TITLE
Create pure Rust version via Corrode

### ISSUE THREAD

**Issue by bwasty** [gltf-rs/mikktspace#10]
The initial idea for this crate was to translate the original MikkTSpace implementation to Rust using [corrode](https://github.com/jameysharp/corrode). This turned out to be trickier than expected, so we went with plain C bindings. In case we want to retry in the future, here are the past findings (copied from https://github.com/gltf-rs/gltf/issues/22):

> I've tried using [corrode](https://github.com/jameysharp/corrode) on the original MikkTSpace implementation, but ran into a few issues:
> * https://github.com/jameysharp/corrode/issues/98
>   - easily solved by changing the syntax in a few dozen places
> * https://github.com/jameysharp/corrode/issues/99
>   - math issue solved with `-ffast-math`
>   - assert issue postponed by commenting out all asserts
> * https://github.com/jameysharp/corrode/issues/22
>   - No idea for a quick solution - `SEdge` is a union and a pretty central data type
> 

The partially adapted code is still available in the `corrode` branch.

**Comment by alteous** [comment]
As a side project, I'm tempted to rewrite this by hand. It's not a very constructive use of time at the moment though for me.

**Comment by alteous** [comment]
Also, see [Citrus](https://gitlab.com/citrus-rs/citrus#citrus-convert-c-to-rust).

**Comment by bwasty** [comment]
Another option: https://github.com/immunant/c2rust (essentially a rewrite of corrode).
