### ISSUE TITLE
Reduce repository size

### ISSUE THREAD

**Issue by bwasty** [gltf-rs/mikktspace#6]
The repository is already quite bloated through the removed Avocado textures - Github shows 8.56MB. Since the repo is young and unpublished I suggest rebasing master to remove it from the history.

@alteous What do you think?

**Comment by bwasty** [comment]
Tried out [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) on my fork (the Github help recommends it for removing large files from the history). The result is pretty nice:
```
$ git clone --mirror https://github.com/bwasty/mikktspace.git
$ java -jar bfg-1.12.15.jar --strip-blobs-bigger-than 100K mikktspace.git     

...

Deleted files
-------------

	Filename                        Git id
	---------------------------------------------------
	Avocado.json                  | d785dd82 (326.7 KB)
	AvocadoOut.obj                | d5f560b9 (144.2 KB)
	Avocado_baseColor.png         | 6f3a8b23 (3.1 MB)
	Avocado_normal.png            | 73f90d59 (3.3 MB)
	Avocado_roughnessMetallic.png | b83cff93 (2.0 MB)
	libmikktspace.a               | e52ce628 (101.4 KB)

...

BFG run is complete! When ready, run: git reflog expire --expire=now --all && git gc --prune=now --aggressive

...

$ git push
```
Result for normal `git clone` afterwards:
cleaned:
`Receiving objects: 100% (177/177), 123.13 KiB | 0 bytes/s, done.`
upstream:
`Receiving objects: 100% (177/177), 8.58 MiB | 2.73 MiB/s, done.`

```
$ du -hs *                                                  
364K	mikktspace
8.8M	mikktspace_upstream
```

So - force-push my master upstream?

**Comment by alteous** [comment]
Sorry, I forgot about this issue.

> So - force-push my master upstream?

Yes, please. Purge at will!

**Comment by bwasty** [comment]
@alteous Done! I also re-created the `corrode` branch.
Don't forget to update your fork (-> https://github.com/gltf-rs/mikktspace/network).

**Comment by alteous** [comment]
Great, will do.

**Comment by alteous** [comment]
Browsing the commit history, we seem to have every commit twice?

**Comment by alteous** [comment]
> Browsing the commit history, we seem to have every commit twice?

Oh, nevermind, it's just GitHub saying the commit hash has changed.

![image](https://user-images.githubusercontent.com/8549126/30771783-2e116f80-a047-11e7-8c2a-281311e4a1c2.png)

**Comment by bwasty** [comment]
No, now all commits are duplicated actually - by your merge commit maybe? 
https://github.com/gltf-rs/mikktspace/commit/e5eedeb330a15c237c6e3bbb12a5371b0062a229

**Comment by alteous** [comment]
Oh **** I didn't mean to do that! :open_mouth: 

I meant to force-update my repo, sorry.

```sh
git remote -v
origin  https://github.com/gltf-rs/mikktspace.git (fetch)                            
origin  https://github.com/gltf-rs/mikktspace.git (push)                             
```
Bloody idiot...

**Comment by alteous** [comment]
I think it's fixed now. Please check it over for me.

**Comment by alteous** [comment]
Lesson learned; this should never happen again!

```sh
git remote -v
origin  https://github.com/alteous/mikktspace-rs.git (fetch)
origin  https://github.com/alteous/mikktspace-rs.git (push)         
```

**Comment by bwasty** [comment]
Looks good again 😄 
(https://github.com/gltf-rs/mikktspace/compare/master...bwasty:master)
